### ISSUE TITLE
Classifier is corrupted 

### ISSUE THREAD

**Issue by ds-jpg** [nowsyn/SIM#11]
Dear author , 

Thank you for your awesome work , but I am facing 1 issue whenever I try to download the classifier it gives me a error stating the file is corrupted , can u pls help me with this , Looking forward to hearing from you. 

Best regards,
Dane

**Comment by Nodice** [comment]
@nowsyn I'm getting the same issue. The tar will not extract, and when trying to load  the state dictionary from classifier_resnet50_best.pth.tar it seems to contain weights from a different model.

Failing at resnet_bn.py at model.load_state_dict(state_dict['state_dict'], strict=True)

**Comment by nowsyn** [comment]
> Dear author ,
> 
> Thank you for your awesome work , but I am facing 1 issue whenever I try to download the classifier it gives me a error stating the file is corrupted , can u pls help me with this , Looking forward to hearing from you.
> 
> Best regards, Dane

I didn't meet the same error when downloading the file. Maybe you need check your network access to make sure you have downloaded the file completely.

**Comment by nowsyn** [comment]
> @nowsyn I'm getting the same issue. The tar will not extract, and when trying to load the state dictionary from classifier_resnet50_best.pth.tar it seems to contain weights from a different model.
> 
> Failing at resnet_bn.py at model.load_state_dict(state_dict['state_dict'], strict=True)

The arch used in the classifier is `resnet50` defined in `networks/resnet.py` instead of the model defined in `networks/resnet_bn.py`. You can refer to `build_classifier` function in main.py for building and loading the classifier.
