### ISSUE TITLE
about SAD of your dataset and weight

### ISSUE THREAD

**Issue by Serge-weihao** [nowsyn/SIM#12]
I think I have correctly generated the test set with your code. but I got 29.58599 SAD with your weight from  https://drive.google.com/file/d/1kmhQtO-6wXTxgHtQCLRj3xPOEtXyzTXC/view?usp=sharing and https://drive.google.com/file/d/12JCGqDylBXJpgDhj4hg_JZYdbHlX8TKe/view?usp=sharing.
![b548f33ab9c559926d5f68088a00443a_2011_001608](https://user-images.githubusercontent.com/40890323/156167651-7301393f-3306-43bf-b7de-c5b576277c10.png)
Fig. 8 row 1 in your paper.

**Comment by Serge-weihao** [comment]
what should I do to get 27.87 SAD?

**Comment by nowsyn** [comment]
We will upload the composited test set directly, so you can download and test on it.
