### ISSUE TITLE
Found 0 samples

### ISSUE THREAD

**Issue by AlexYez** [nowsyn/SIM#5]
Hi!
I installed all the dependencies, download models and changed these lines: 45 and 48 in networks/model.py to have pretrained=False
I have set up config.yaml and put .png and .jpg photos to images folder
But after running the script i got:
2021-10-13 15:37:29,564-main.py:33-INFO-=> creating classifier 'resnet50'
2021-10-13 15:37:29,831-main.py:36-INFO-=> loading checkpoint 'checkpoints/classifier_resnet50_best.pth.tar'
2021-10-13 15:37:29,878-main.py:40-INFO-=> loaded checkpoint 'checkpoints/classifier_resnet50_best.pth.tar'
modifying input layer to accept 11 channels
2021-10-13 15:37:30,393-main.py:63-INFO-Pretrain: no checkpoint found at 'None'
2021-10-13 15:37:30,393-main.py:66-INFO-Resume: loading 'checkpoints/SIM/ckpt_best.pth'
2021-10-13 15:37:30,520-main.py:71-INFO-Resume: loaded 'checkpoints/SIM/ckpt_best.pth'
Found 0 samples
Found 0 samples
2021-10-13 15:37:32,148-main.py:291-INFO-Test: Time 0.000 (0.000)
2021-10-13 15:37:32,148-main.py:296-INFO-MeanSAD: 0.000

How can I test pretrained models on my own images?

**Comment by dongdong93** [comment]
Hi, thank you for sharing the dataset. I did not find 'trimap' or 'merged' folders in the test folder of SIMD dataset. Did I miss anything?

**Comment by ptrmcl** [comment]
@AlexYez You need to write your own code for that I believe.

**Comment by zhanghongyong123456** [comment]
> Hi! I installed all the dependencies, download models and changed these lines: 45 and 48 in networks/model.py to have pretrained=False I have set up config.yaml and put .png and .jpg photos to images folder But after running the script i got: 2021-10-13 15:37:29,564-main.py:33-INFO-=> creating classifier 'resnet50' 2021-10-13 15:37:29,831-main.py:36-INFO-=> loading checkpoint 'checkpoints/classifier_resnet50_best.pth.tar' 2021-10-13 15:37:29,878-main.py:40-INFO-=> loaded checkpoint 'checkpoints/classifier_resnet50_best.pth.tar' modifying input layer to accept 11 channels 2021-10-13 15:37:30,393-main.py:63-INFO-Pretrain: no checkpoint found at 'None' 2021-10-13 15:37:30,393-main.py:66-INFO-Resume: loading 'checkpoints/SIM/ckpt_best.pth' 2021-10-13 15:37:30,520-main.py:71-INFO-Resume: loaded 'checkpoints/SIM/ckpt_best.pth' Found 0 samples Found 0 samples 2021-10-13 15:37:32,148-main.py:291-INFO-Test: Time 0.000 (0.000) 2021-10-13 15:37:32,148-main.py:296-INFO-MeanSAD: 0.000
> 
> How can I test pretrained models on my own images?

I have the same problem as you, how did you solve it? I'm looking forward to your help  ，How do I test my own data when I only have an RGB image

**Comment by largerwxt** [comment]
I have the same problem as you, how did you solve it?  I'm looking forward to your help，thanks!

**Comment by nowsyn** [comment]
You can use dataset/generate_testset.py to generate the benchmark we used first. If you want to test on your own data, you are supposed to prepare images and trimaps.

**Comment by EagleAiDi** [comment]
Hi! Thank you for your reply!                                                                                                                                                                 modifying input layer to accept 11 channels
2023-06-15 20:35:20,796-main.py:63-INFO-Pretrain: no checkpoint found at 'None'
2023-06-15 20:35:20,796-main.py:73-INFO-Resume: no checkpoint found at 'checkpoints/SIM/ckpt_best.pth'
2023-06-15 20:35:23,832-main.py:291-INFO-Test: Time 0.000 (0.000)
2023-06-15 20:35:23,832-main.py:296-INFO-MeanSAD: 0.000
Found 0 samples
Found 0 samples                                                                                                                                                                                             I also encountered the same issue and read your response.I'm sorry, but I still don't quite understand how to proceed. Could you please provide a more detailed explanation?
